-- 插入测试数据到 outbound_message 表
INSERT INTO outbound_message (msg_id, msg_type, sender_bic, receiver_bic, raw_content, status, retry_count) VALUES
('OUT-MSG-001', 'pacs.008', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>OUT-MSG-001</BizMsgIdr></AppHdr><Document><FIToFICstmrCdtTrf><GrpHdr><MsgId>OUT-MSG-001</MsgId></GrpHdr></FIToFICstmrCdtTrf></Document>', 'PENDING_ROUTING', 0),
('OUT-MSG-002', 'pacs.002', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>OUT-MSG-002</BizMsgIdr></AppHdr><Document><FIToFIPmtStsRpt><GrpHdr><MsgId>OUT-MSG-002</MsgId></GrpHdr></FIToFIPmtStsRpt></Document>', 'PENDING_ROUTING', 0);

-- 插入测试数据到 inbound_message 表
INSERT INTO inbound_message (msg_id, msg_type, sender_bic, receiver_bic, raw_content, status, retry_count) VALUES
('IN-MSG-001', 'pacs.008', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>IN-MSG-001</BizMsgIdr></AppHdr><Document><FIToFICstmrCdtTrf><GrpHdr><MsgId>IN-MSG-001</MsgId></GrpHdr></FIToFICstmrCdtTrf></Document>', 'PENDING_ROUTING', 0),
('IN-MSG-002', 'pacs.002', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>IN-MSG-002</BizMsgIdr></AppHdr><Document><FIToFIPmtStsRpt><GrpHdr><MsgId>IN-MSG-002</MsgId></GrpHdr></FIToFIPmtStsRpt></Document>', 'PENDING_ROUTING', 0),
('IN-MSG-003', 'pacs.008', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>IN-MSG-003</BizMsgIdr></AppHdr><Document><FIToFICstmrCdtTrf><GrpHdr><MsgId>IN-MSG-003</MsgId></GrpHdr></FIToFICstmrCdtTrf></Document>', 'IN_PROGRESS', 0),
('IN-MSG-004', 'pacs.002', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>IN-MSG-004</BizMsgIdr></AppHdr><Document><FIToFIPmtStsRpt><GrpHdr><MsgId>IN-MSG-004</MsgId></GrpHdr></FIToFIPmtStsRpt></Document>', 'DELIVERED', 0),
('IN-MSG-005', 'pacs.008', 'SENDERBIC', 'RECEIVERBIC', '<AppHdr><Fr><FIId><FinInstnId><BICFI>SENDERBIC</BICFI></FinInstnId></FIId></Fr><To><FIId><FinInstnId><BICFI>RECEIVERBIC</BICFI></FinInstnId></FIId></To><BizMsgIdr>IN-MSG-005</BizMsgIdr></AppHdr><Document><FIToFICstmrCdtTrf><GrpHdr><MsgId>IN-MSG-005</MsgId></GrpHdr></FIToFICstmrCdtTrf></Document>', 'FAILED', 0);